# azure spirng apps action
name: 'Azure Spring Apps'
description: 'Deploy applications to Azure Spring Apps and manage deployments.'
inputs: 
  azure-subscription:
    description: 'Select the Azure Resource Manager subscription for the deployment.'
    required: true
  action:
    description: 'Action to be performed on Azure Spring Apps.'
    required: true
    default: 'deploy'
  service-name:
    description: 'Select the Azure Spring Apps service to which to deploy.'
    required: true
  app-name:
    description: 'Select the Azure Spring Apps app to deploy.'
    required: true
  use-staging-deployment:
    description: "Automatically select the deployment that's set as Staging at the time the task runs."
    required: true
    default: true
  create-new-deployment:
    description: "Whether to target the deployment that's set as Staging at the time of execution. If unchecked, the 'Deployment Name' setting must be set."
    required: false
    default: false
  deployment-name:
    description: 'The deployment to which this task will apply. Lowercase letters, - and numbers only; must start with a letter.'
    required: false
  package:
    description: "File path to the package or a folder containing the Spring Apps app contents."
    required: false
    default: '${{ github.workspace }}/**/*.jar'
  cpu:
    description: "The CPU resource quantity. It should be 500m or number of CPU cores. It is effective only when creating new deployment."
    required: false
    default: '1'
  memory:
    description: "The memory resource quantity. It should be 512Mi or #Gi, e.g., 1Gi, 3Gi. It is effective only when creating new deployment."
    required: false
    default: '1Gi'      
  environment-variables:
    description: "Edit the app's environment variables."
    required: false
  jvm-options:
    description: "Edit the app's JVM options. A String containing JVM Options. Example: `-Xms1024m -Xmx2048m`"
    required: false
  runtime-version:
    description: 'The runtime on which the app will run.'
    required: false
  dotnetcore-mainentry-path:
    description: 'The path to the .NET executable relative to zip root.'
    required: false
  version:
    description: 'The runtime on which the app will run.'
    required: false
  build-name:
    description: '(Enterprise Tier Only) The build name.'
    required: false
  builder:
    description: '(Enterprise Tier Only) Build service builder used to build the executable.'
    required: false
  build-cpu:
    description: '(Enterprise Tier Only) CPU resource quantity for build container. Should be 500m or number of CPU cores. Default: 1'
    required: false
  build-memory:
    description: '(Enterprise Tier Only) Memory resource quantity for build container. Should be 512Mi or #Gi, e.g., 1Gi, 3Gi. Default: 2Gi.'
    required: false
  build-env:
    description: "(Enterprise Tier Only) Space-separated environment variables for the build process in 'key[=value]' format."
    required: false
  config-file-patterns:
    description: "(Enterprise Tier Only) Config file patterns separated with ',' to decide which patterns of Application Configuration Service will be used. Use '\"\"' to clear existing configurations."
    required: false
  container-registry:
    description: "The registry of the container image.  Default: docker.io."
    required: false
    default: "docker.io"
  registry-username:
    description: "The username of the container registry."
    required: false
  registry-password:
    description: "The password of the container registry."
    required: false
  container-image:
    description: "The container image."
    required: false
  container-command:
    description: "The command of the container."
    required: false
  container-args:
    description: "The arguments of the container."
    required: false
  language-framework:
    description: "The language framework of the container."
    required: false


branding:
  icon: 'icon.svg'
runs:
  using: 'node12'
  main: 'lib/main.js'
  